name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:  # Добавляем возможность ручного запуска
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      skip-tests:
        description: 'Skip unit tests?'
        required: false
        default: false
        type: boolean

jobs:
  test:
    if: ${{ !inputs.skip-tests }}  # Пропускаем тесты если выбрано skip-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
    
    - name: Run unit tests
      run: go test -v -coverprofile=coverage.out ./...
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
    
  create-merge-request:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Merge Request
      uses: peter-evans/create-pull-request@v5
      with:
        base: test
        branch: auto-merge-to-test-${{ github.run_id }}  # Уникальное имя ветки
        title: "Auto-merge [${{ inputs.environment }}]: Test results successful"
        body: |
          Automated merge request after successful unit tests
          Environment: ${{ inputs.environment }}
          Run ID: ${{ github.run_id }}
        labels: "automated,${{ inputs.environment }}"