name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip unit tests?'
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
    
    - name: Run unit tests
      run: go test -v -coverprofile=coverage.out ./...
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
    
  check-branch-exists:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      branch_exists: ${{ steps.check-branch.outputs.exists }}
    steps:
    - name: Check if test branch exists
      id: check-branch
      run: |
        if git ls-remote --exit-code --heads origin test; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

  create-merge-request:
    needs: check-branch-exists
    if: needs.check-branch-exists.outputs.branch_exists == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Merge Request
      uses: peter-evans/create-pull-request@v5
      with:
        base: test
        branch: auto-merge-to-test-${{ github.run_id }}
        title: "Auto-merge: Test results successful"
        body: "Automated merge request after successful unit tests"
        labels: "automated"

  create-branch-and-pr:
    needs: check-branch-exists
    if: needs.check-branch-exists.outputs.branch_exists == 'false'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create test branch
      run: |
        git checkout -b test
        git push origin test
    
    - name: Create initial PR to test branch
      uses: peter-evans/create-pull-request@v5
      with:
        base: test
        branch: initial-setup-${{ github.run_id }}
        title: "Initial setup of test branch"
        body: "Creating test branch for future merges"
        labels: "automated,setup"