name: Run Unit-Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip unit tests?'
        required: false
        default: false
        type: boolean
      create-mr:
        description: 'Create Pull Request?'
        required: false
        default: false
        type: boolean

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'
    
    - name: Run unit tests
      if: ${{ !inputs.skip-tests }}
      run: go test -v -coverprofile=coverage.out ./...
    
    - name: Upload coverage
      if: ${{ !inputs.skip-tests }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out

  trigger-mr:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger MR workflow on success
      uses: actions/github-script@v6
      if: ${{ inputs.create-mr }}
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'create-mr.yml',
            ref: 'dev',
          });